version: '3.8'

services:
  weather-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: emerald-hills-weather
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    env_file:
      - .env
    volumes:
      - weather-data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.weather.rule=Host(`weather.emerald-hills.local`)"
      - "traefik.http.services.weather.loadbalancer.server.port=3001"

  # Optional: Reverse proxy for SSL and domain routing
  traefik:
    image: traefik:v2.10
    container_name: weather-proxy
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    profiles:
      - proxy

volumes:
  weather-data:
    driver: local